"""add_phase4_email_intelligence_fields

Revision ID: 1e3c96d0b0a0
Revises: b5ebee75f549
Create Date: 2026-09-08 10:32:49.727293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3c96d0b0a0'
down_revision = 'b5ebee75f549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_status', sa.String(length=50), nullable=False, server_default='pending'))
        batch_op.add_column(sa.Column('ai_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ai_priority', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ai_sentiment', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ai_action_required', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('ai_deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ai_processed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ai_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ai_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_suggested_tasks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_suggested_event', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_email_messages_ai_status'), ['ai_status'], unique=False)

    op.execute("UPDATE email_messages SET ai_status = 'pending' WHERE ai_status IS NULL OR ai_status = ''")
    op.execute("UPDATE email_messages SET ai_action_required = false WHERE ai_action_required IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_messages_ai_status'))
        batch_op.drop_column('ai_suggested_event')
        batch_op.drop_column('ai_suggested_tasks')
        batch_op.drop_column('ai_error')
        batch_op.drop_column('ai_model')
        batch_op.drop_column('ai_processed_at')
        batch_op.drop_column('ai_deadline')
        batch_op.drop_column('ai_action_required')
        batch_op.drop_column('ai_sentiment')
        batch_op.drop_column('ai_priority')
        batch_op.drop_column('ai_category')
        batch_op.drop_column('ai_summary')
        batch_op.drop_column('ai_status')

    # ### end Alembic commands ###
