"""phase5_smart_tasks_calendar

Revision ID: 28814bc4372b
Revises: 1e3c96d0b0a0
Create Date: 2026-09-08 11:09:16.026988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28814bc4372b'
down_revision = '1e3c96d0b0a0'
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Add columns as nullable first
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # Step 2: Backfill existing records
    op.execute(
        "UPDATE tasks SET user_id = (SELECT user_id FROM email_messages WHERE email_messages.id = tasks.email_id)"
    )
    op.execute(
        "UPDATE tasks SET updated_at = created_at WHERE updated_at IS NULL"
    )
    # Normalize legacy status values to lowercase if needed
    op.execute(
        "UPDATE tasks SET status = LOWER(status) WHERE status IS NOT NULL"
    )

    op.execute(
        "UPDATE calendar_events SET user_id = (SELECT user_id FROM email_messages WHERE email_messages.id = calendar_events.email_id)"
    )
    op.execute(
        "UPDATE calendar_events SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL"
    )
    op.execute(
        "UPDATE calendar_events SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL"
    )

    # Step 3: Verify no null user_id remains
    conn = op.get_bind()
    task_nulls = conn.execute(sa.text("SELECT count(*) FROM tasks WHERE user_id IS NULL")).scalar()
    if task_nulls and task_nulls > 0:
        raise RuntimeError(f"Migration aborted: {task_nulls} tasks have no determinable owner!")

    cal_nulls = conn.execute(sa.text("SELECT count(*) FROM calendar_events WHERE user_id IS NULL")).scalar()
    if cal_nulls and cal_nulls > 0:
        raise RuntimeError(f"Migration aborted: {cal_nulls} calendar events have no determinable owner!")

    # Step 4: Enforce NOT NULL, add foreign keys, indices, and make email_id nullable
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.String(length=36), nullable=False)
        batch_op.alter_column('updated_at', existing_type=sa.DateTime(), nullable=False)
        batch_op.alter_column('email_id', existing_type=sa.VARCHAR(length=36), nullable=True)
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_tasks_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.String(length=36), nullable=False)
        batch_op.alter_column('created_at', existing_type=sa.DateTime(), nullable=False)
        batch_op.alter_column('updated_at', existing_type=sa.DateTime(), nullable=False)
        batch_op.alter_column('email_id', existing_type=sa.VARCHAR(length=36), nullable=True)
        batch_op.drop_index(batch_op.f('ix_calendar_events_email_id'))
        batch_op.create_index(batch_op.f('ix_calendar_events_email_id'), ['email_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_start_date_time'), ['start_date_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_calendar_events_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))
        batch_op.alter_column('email_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_calendar_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_start_date_time'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_email_id'))
        batch_op.create_index(batch_op.f('ix_calendar_events_email_id'), ['email_id'], unique=1)
        batch_op.alter_column('email_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
