"""add_phase2_email_message_sync_fields

Revision ID: b5ebee75f549
Revises: dfccaaaa782e
Create Date: 2026-09-08 09:02:35.602695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ebee75f549'
down_revision = 'dfccaaaa782e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connected_account_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('provider_message_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recipients', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bcc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('labels', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('has_attachments', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('attachment_metadata', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('raw_metadata', sa.Text(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_email_messages_message_id'))
        batch_op.create_index(batch_op.f('ix_email_messages_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_messages_connected_account_id'), ['connected_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_messages_provider_message_id'), ['provider_message_id'], unique=False)
        batch_op.create_unique_constraint('uq_connected_account_provider_msg', ['connected_account_id', 'provider_message_id'])
        batch_op.create_foreign_key('fk_email_messages_connected_account', 'connected_email_accounts', ['connected_account_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_email_messages_connected_account', type_='foreignkey')
        batch_op.drop_constraint('uq_connected_account_provider_msg', type_='unique')
        batch_op.drop_index(batch_op.f('ix_email_messages_provider_message_id'))
        batch_op.drop_index(batch_op.f('ix_email_messages_connected_account_id'))
        batch_op.drop_index(batch_op.f('ix_email_messages_message_id'))
        batch_op.create_index(batch_op.f('ix_email_messages_message_id'), ['message_id'], unique=1)
        batch_op.drop_column('raw_metadata')
        batch_op.drop_column('attachment_metadata')
        batch_op.drop_column('has_attachments')
        batch_op.drop_column('labels')
        batch_op.drop_column('bcc')
        batch_op.drop_column('cc')
        batch_op.drop_column('recipients')
        batch_op.drop_column('body_html')
        batch_op.drop_column('provider_message_id')
        batch_op.drop_column('connected_account_id')

    # ### end Alembic commands ###
